spring:
  #spring application
  application:
    name: api-gateway
  #spring cloud gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      # custom api gateway routes
      routes:
        - id: product-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/products/**
          filters:
            #RateLimiter
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@userKeyResolver}'
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                redis-rate-limiter.requestedTokens: 1
  #config redis
  data:
    redis:
      host: localhost
      port: 6379

#spring boot actuator
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

#logging
logging:
  level:
    root: INFO
    #org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    #org.springframework.cloud.gateway: DEBUG
    #org.springframework.cloud.loadbalancer: DEBUG

#config register to eureka-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      initialInstanceInfoReplicationIntervalSeconds: 5
      registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

#config port
server:
  port: 8168

