#spring application
spring:
  application:
    name: product-service

#config datasource
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ecommerce_db
    username: postgres
    password: 1234
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    show-sql: true

#config port
server:
  port: 8081

#config register to eureka-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      initialInstanceInfoReplicationIntervalSeconds: 5
      registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
